name: eternaltalk_app
description: EternalTalk Flutter Template (Overlay)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  go_router: ^14.2.7
  flutter_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png          # 무한대 로고
    - assets/images/text_logo.png     # EternalTalk 글씨
